CREATE SCHEMA ecommerce_analysis OPTIONS(location="US");
CREATE OR REPLACE TABLE ecommerce_analysis.big_orders AS
SELECT
  GENERATE_UUID() AS order_id,
  RAND()*1000 AS price,
  TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL CAST(RAND()*365 AS INT64) DAY) AS order_date
FROM UNNEST(GENERATE_ARRAY(1, 1000000));